name: Test Build
on:
  workflow_dispatch:


jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1

      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Make Directory for results
        run: mkdir -p testResults

      - name: Run POSTMAN collection
        if: failure()
        run: |
          newman run petstore.collection.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme  > testResults/runreport1.html
        
      - name: Output the run Details
        uses: actions/upload-artifact@v3.1.0
        if: always()
        with:
          name: RunReports
          path: testResults

#       - name: Deploy report
#         uses: JamesIves/github-pages-deploy-action@v4.4.0
#         if: always()
#         with:
#           branch: gh-pages
#           folder: testResults
